### ISSUE TITLE
Error in the generator for non IXPE related tables

### ISSUE THREAD

**Issue by SamuelBarnier** [mbursa/xspec-table-models#1]
Hi Michal !

I think there might be a small error in the generator function line 197:
`                p_index = int((global_index/3)//N0 % N)`
Here the number 3 should be self.NXFLTEXP I think. It stays 3 in the case of an IXPE table and 1 in the case of a 'normal' xspec table.

If you keep the number 3 and try to produce a 'normal' Xspec table (not IXPE related), it will not sweep all the parameter space, repeating some parameter sets.

Best,
Samuel

**Comment by mbursa** [comment]
Many thanks, Samuel! Fixed in 12ce996576ded87aebab814d4f30332566709e06. (I must have missed the notification, so apologies for the delay.)
